version: '3.8'

services:
  backend:
    container_name: backend
    build:
      context: ./BE
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      - SPRING_DATA_MONGODB_HOST=mongo
      - SPRING_DATA_MONGODB_PORT=27017
    restart: on-failure
  mongo:
    container_name: database
    image: mongo:latest
    ports:
      - "27018:27017"
    volumes:
      - mongo-db:/data/db
  frontend_app:
    container_name: frontend
    build:
      context: ./FE
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - "./FE/nginx.conf:/etc/nginx/nginx.conf"
    restart: on-failure

volumes:
  mongo-db:
