openapi: 3.0.3
info:
  title: Rejstracja do systemu erasmus - OpenAPI 3.0
  description: |-
    Rejestracja do systemu Erasmus 
    - API służące do rejestracji studentów w systemie Erasmus.
    
    Some useful links:
    - [The Pet Store repository](https://github.com/swagger-api/swagger-petstore)
    - [The source API definition for the Pet Store](https://github.com/swagger-api/swagger-petstore/blob/master/src/main/resources/openapi.yaml)
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 0.0.1-SNAPSHOT
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: http://localhost:8080
tags:
  - name: UserContextSecurity
    description: Everything about security in the user context

paths:
  /user/sign-up:
    post:
      tags:
        - UserContextSecurity
      summary: Sign Up to the system
      description: Create user account
      operationId: createAccount
      requestBody:
        description: Filled form of user account
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignUpForm'
        required: true
      responses:
        '200':
          description: User account created successfully.
        '400':
          description: Bad Request - Invalid input data.
        '500':
          description: Internal server error - Unable to create user account.

  /user/login:
    post:
      tags:
        - UserContextSecurity
      summary: Log in to the system
      description: Authenticate user credentials and generate access token
      operationId: authenticateUser
      requestBody:
        description: User credentials for authentication
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                  description: User's email address
                password:
                  type: string
                  format: password
                  description: User's password for the account
              required:
                - email
                - password
      responses:
        '200':
          description: Authentication successful, returns access token.
          content:
            application/json:
              schema:
                type: object
                properties:
                  accessToken:
                    type: string
                    description: Access token for authenticated user.
        '401':
          description: Unauthorized - Invalid user credentials.
        '500':
          description: Internal server error - Unable to authenticate user.


components:
  schemas:
    SignUpForm:
      type: object
      properties:
        name:
          type: string
          description: User's first name
        surname:
          type: string
          description: User's last name
        email:
          type: string
          format: email
          description: User's email address
        password:
          type: string
          format: password
          description: User's password for the account
      required:
        - name
        - surname
        - email
        - password