##
### Configuration for production
##
spring:
  data:
    mongodb:
      port: 27017
      host: localhost
      database: test_db
      username: #<Username>
      password: # <Password>
      authentication-database: # <Authentication>
  servlet:
    multipart:
      enabled: true
      max-request-size: 20MB
      max-file-size: 2MB

jwt:
  token:
    secretKey: someSecretKey
    expirationSec: 300            # 5 min
    refreshExpirationSec: 900     # 15min
    header: Authorization
    prefix: Bearer